version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/scheduler"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    labels:
      - "v2"
      - "dependencies"
    reviewers:
      - lc525

  - package-ecosystem: "gradle"
    directory: "/scheduler/data-flow"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    labels:
      - "v2"
      - "dependencies"
    reviewers:
      - lc525

  - package-ecosystem: "docker"
    directory: "/scheduler"
    target-branch: "v2"
    schedule:
      interval: "weekly"
    labels:
      - "v2"
      - "dependencies"
    reviewers:
      - lc525
