name: docs-gb-update-file-references

on:
  pull_request:
    branches:
      - 'release-**'
    types:
      - opened
      - reopened
      - edited

jobs:
  update-docs-gb-file-references:
    # if: github.repository == 'SeldonIO/seldon-core' # Do not run this on forks.
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_USER}"
          git config --global user.email "${GITHUB_USER}@users.noreply.github.com"

      - name: Update file references in docs
        run: |
          make docs-gitbook-update-code-references
          git add .
          git commit -m "Update file references in docs"
          git push
        env:
          RELEASE_BRANCH_REF: ${{ github.base_ref }}
